// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnkexgmcteqeeztkjanc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJua2V4Z21jdGVxZWV6dGtqYW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NDA5NTMsImV4cCI6MjA3NzExNjk1M30.gnx7lPwvj09Fih6rQfKriwi8MF-tz1ULWNCnyksvOXU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});